---
title: "The OpenBiomechanics Project"
subtitle: "The Open Source Initiative for Anonymized, Elite-Level Athletic Motion Capture Data"
output: 
  bookdown::pdf_document2:
    toc: false
    keep_tex: true
    subparagraph: yes
    includes:
      in_header: preamble.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
# set to false if you need to view the accessory latex files
options(tinytex.clean = FALSE)

# this function is needed to remove extra author block in compiled tex doc
# solution found at:
  # https://issueexplorer.com/issue/rstudio/bookdown/1158
remove_author <- function(x) {
  # identify empty author line
  i <- grep("^\\\\author\\{\\}$", x)
  # be sure it is the one pandoc inserts
  if(length(i) != 0 && grepl('^\\\\date\\{', x[i+1])) x <- x[-i]
  x
}
options(bookdown.post.latex = remove_author)
```

\pagenumbering{gobble}
\begin{center}
Keywords: open access, baseball, pitching
\end{center}

\bigskip
\bigskip
\linenumbers
\doublespacing
\begin{abstract}
Interest in quantifying human movement, particularly in elite sport, increases with each passing year. However, analysis of sport biomechanics data has traditionally been restricted to academic laboratories and professional sport organizations. A public sport biomechanics resource would democratize access to human movement data and accelerate progress and innovation for the sport biomechanics field as a whole. In this paper, we introduce \href{www.openbiomechanics.org}{\textbf{\textit{The OpenBiomechanics Project}}}, an initiative started by \href{https://www.drivelinebaseball.com/research/}{\textbf{\textit{Driveline Baseball Research \& Development}}} to provide free, elite-level, research grade motion capture data to the general public for independent individual exploration and analysis. We begin by providing raw and processed data from a sample of 100 baseball pitchers. We then discuss future directions within baseball, expansion to other sports and athletic movements, and outline supporting documentation and additional resources.
\end{abstract}

\newpage
# Introduction

Open access resources exist in other biomechanics sub disciplines \cite{camargo2021comprehensive, erdemir2016open}. 

# Data collection

Data collection took place at Driveline Baseball in Kent, Washington, USA as part of each athlete's motion capture assessment. After a standardized warm up consisting of static and dynamic stretching, resistance band exercises, and preparatory throwing drills, we applied between 45 and 48 reflective markers directly to the athlete's skin over relevant bony landmarks (Table \ref{tbl:marker_set}). We then allowed athletes to complete a final warm up consisting of preparatory throws from the pitching mound. Once the athlete indicated they felt ready to throw with game-like effort, we recorded up to five fastball pitches from a pitching mound at a regulation distance (18.4 m). 

Although athletes were cued to throw at the provided strike zone, we did not require athletes to throw a strike for a trial to be considered valid. We considered a trial valid if all reflective markers remained affixed to the athlete throughout the pitching motion. Pitch velocities were measured to the nearest tenth of a mile per hour using a radar gun positioned behind home plate and paired with each trial prior to processing and analysis.

Marker positions were recorded at 360 Hz by fourteen cameras (Prime 17W; Optitrack/NaturalPoint Inc., Corvallis, OR, USA) while ground reaction force data were collected at 1,080 Hz by three force plates embedded in a custom concrete mound (1 x FP4080-15-TM-2000, 2 x FP9090-15-TM-2000; Bertec Corp., Columbus, OH, USA). Kinematic and kinetic data were synchronized using Optitrack's Motive software. Once we collected a sufficient number of pitches (typically between three and five trials), C3D files were exported for processing in Visual3D and Python.

\begin{table}[h]
\centering
\begin{threeparttable}
\begin{tabular}{C{0.25\textwidth}C{0.375\textwidth}R{0.375\textwidth}}
\toprule
\multicolumn{1}{c}{Abbreviation} & \multicolumn{1}{c}{Rigid Body} & \multicolumn{1}{c}{Description} \\
\cline{1-3}
C7 & Thorax & Seventh cervical vertebrae \\
CLAV & Thorax & Jugular notch \\
LANK & Left shank, left foot & Left ankle lateral malleolus \\
LASI & Pelvis & Left anterior superior iliac spine \\
LBAK\tnote{a} & Thorax & Left scapular inferior angle \\
LBHD & Head & Left, posterior \\
LELB & Left upper arm, left forearm & Left lateral humeral epicondyle \\
LFHD & Head & Left, anterior \\
LFIN & Left hand & Third metacarpophalangeal joint \\
LFRM & Left forearm & Left forearm \\
LHEE & Left foot & Heel \\
LIC\tnote{a} & Pelvis & Left iliac crest \\
LKNE & Left thigh, left shank & Left lateral femoral condyle \\
LMANK & Left shank, left foot & Left ankle medial malleolus \\
LMELB & Left upper arm, left forearm & Left medial humeral epicondyle \\
LMKNE & Left thigh, left shank & Left medial femoral condyle\\
LPSI & Pelvis & Left posterior superior iliac spine \\
LSHO & Left upper arm & Left acromial plateau \\
LTHI & Left thigh & Left thigh \\
LTIB & Left shank & Left shank \\
LTOE & Left foot & Left second metatarsophalangeal joint \\
LUPA & Left upper arm & Left upper arm \\
LWRA & Left forearm, left hand & Left radial styloid \\
LWRB & Left forearm, left hand & Left ulnar styloid \\
RANK & Right shank, right foot & Right ankle lateral malleolus\\
RASI & Pelvis & Right anterior superior iliac spine \\
RBAK & Thorax & Right scapular inferior angle \\
RBHD & Head & Right, posterior \\
RELB & Right upper arm, right forearm & Right lateral humeral epicondyle \\
RFHD & Head & Right, anterior \\
RFIN & Right hand & Third metacarpophalangeal joint \\
RFRM & Right forearm & Right forearm \\
RHEE & Right foot & Right heel \\
RIC\tnote{a} & Pelvis & Right iliac crest \\
RKNE & Right thigh, right shank & Right lateral femoral condyle \\
RMANK & Right shank, right foot & Right ankle medial malleolus \\
RMELB & Right upper arm, right forearm & Right medial humeral epicondyle \\
RMKNE & Right thigh, right shank & Right medial femoral condyle\\
RPSI & Pelvis & Right posterior superior iliac spine \\
RSHO & Right upper arm & Right acromial plateau \\
RTHI & Right thigh & Right thigh \\
RTIB & Right shank & Right shank \\
RTOE & Right foot & Right second metatarsophalangeal joint \\
RUPA & Right upper arm & Right upper arm \\
RWRA & Right forearm, right hand & Right radial styloid \\
RWRB & Right forearm, right hand & Right ulnar styloid \\
STRN & Thorax & Xiphoid Process \\
T10 & Thorax & Tenth thoracic vertebrae \\
\hhline{===}
\end{tabular}
\begin{tablenotes}[flushleft]
\scriptsize{
\item[a] Left back and iliac crest markers were removed from our marker set in 2021. Therefore, LBAK/LIC/RIC markers may not be present in all C3D files
}
\end{tablenotes}
\end{threeparttable}
\label{tbl:markerset}
\end{table}

# Data processing

C3D files meeting the validity criteria were exported from Motive. Where necessary, we used cubic spline and pattern-based gap filling techniques prior to export to interpolate occluded marker positions. C3D files were then fed into a custom Visual3D processing pipeline for pose estimation and inverse dynamics calculations.

## Linked-Segment Model

Our full-body skeletal model consisted of 14 body segments [bilateral feet (1-2), shanks (3-4), thighs (5-6), upper arms (7-8), forearms (9-10), and hands (11-12), plus a pelvis (13) and thorax (14)] separated into four inverse dynamics linkages representing the four limbs of the body. The pelvis and thorax were left unconstrained (6 DOF) with respect to the linkages and with respect to each other. 

We used default Visual3D segment mass/body mass ratios, inertial parameters, and segment geometries \cite{dempster1955space, hanavan1964mathematical}. The hip joint centers and pelvis segment were modeled using Bell's CODA methods \cite{bell1989prediction, bell1990comparison}. Joint centers for the elbows, wrists, knees, and ankles were defined as the midpoint between the joint's medial and lateral markers. Shoulder joint centers were offset relative to the acromion markers \cite{schmidt1999marker}. Complete model specifications may be found in the .MDH file provided in the \href{https://github.com/drivelineresearch/openbiomechanics/tree/main/baseball_pitching/code/v3d/model}{\textbf{\textit{OBP GitHub repository}}}.

# How to Use

Data for the OpenBiomechanics Project may be found in our GitHub repository linked previously in this article. Although single-use downloads are possible, we recommend familiarizing yourself with the source control program \textit{git}, if you are not already. Using \textit{git} best practices ensures that your data and code remain updated in the event of any patches, changes, or new releases. For most users, the application \href{https://desktop.github.com/}{\textit{\textbf{GitHub Desktop}}} will suffice, and comes with supporting tutorials and documentation.

Once you have GitHub desktop (or an analogous \textit{git} solution) in place, simply fork our repository to create your own branch from which you can customize our code and analyze our data. Any changes or additions you commit will remain on your branch, allowing all users to perform their own analyses without interference from other researchers.

## Terms of Use

Data and code provided through the OpenBiomechanics project are protected under a Creative Commons license and free for individual use. Researchers 

## Naming Conventions

...

## Fileshare and GitHub Repository

...

## Citing and Contributing

...

# Future Directions

...

# Additional Resources

...

<!----------------------------------------------------------References--->

\newpage
\singlespacing
\addcontentsline{toc}{section}{References}
\bibliographystyle{plain-custom}
\bibliography{openBiomech}